version: "3.8"

services:
  ttsbot:
    build: '.'
    container_name: "$CONTAINER_NAME-bot"
    restart: always
    networks:
      - tts
  pfdb:
    image: bianjp/mariadb-alpine:latest
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    container_name: "$CONTAINER_NAME-db"
    networks:
      tts:
        aliases:
          - "${CONTAINER_NAME}db"
    volumes:
      - db_data:/var/lib/mysql      
    restart: always
volumes:
    db_data:
networks:
     tts: